### PR TITLE
Making it compile on Linux

### PR DESCRIPTION
**Pull request by max-baz**
I was playing with your repo while looking at https://github.com/emojione/emojione/issues/524, these are the changes that I had to make in order to make it compile:

- The way your `rename` command works is it generates one large command to execute, the length of this command is so big that my shell did not want to accept it. The build was failing with `make: execvp: /bin/sh: Argument list too long`. The trick is to use new-lines, so that each rename command is executed separately.

- `python` defaults to python 3 by default, however something in fonttools or noto-tools cannot be compiled with python3. Most systems have aliases `python3` and `python2` in addition to `python`, here I'm using `python2` to force execution with that version of python.

Have a look if you want to merge everything or parts of it.

### CODE REVIEW

**Comment by jbicha** [comment]
> python defaults to python 3 by default

Only on Arch Linux.

nototools is currently python2 only. See https://github.com/googlei18n/nototools/issues/463

**Comment by max-baz** [comment]
Exactly my point, using `python` is not always compatible with nototools, thus the change to use `python2`.

**Comment by jbicha** [comment]
@maximbaz Why don't you propose it [upstream](https://github.com/googlei18n/noto-emoji/issues) then?

**Comment by max-baz** [comment]
Simply never got to do it, we can't use noto-emoji for building EmojiOne anyway because of [noto-emoji#9](https://github.com/googlei18n/noto-emoji/issues/9), so it was not a priority for me. Nobody else seems to have issues with how python is used anyway. 

Maybe by the time [noto-emoji#9](https://github.com/googlei18n/noto-emoji/issues/9) is fixed, nototools will support python3 😜

**Pull request merged**
